// ── Central data for all holiday packages ──────────────────────────────────

export const holidayCategories = [
  {
    id: "holiday-packages",
    label: "Holiday Packages",
    tagline: "All-inclusive curated trips",
    coverImage: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
    color: "#c7d300",
    packages: [
      {
        id: "dubai-5n",
        title: "Dubai Splendour",
        destination: "Dubai, UAE",
        duration: "5N / 6D",
        price: "₹45,000",
        image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
        highlights: ["Burj Khalifa", "Desert Safari", "Dubai Mall", "Palm Jumeirah", "Dubai Frame"],
        itinerary: [
          { day: 1, title: "Arrival & City Tour", desc: "Airport pickup, hotel check-in, evening Dubai Marina walk." },
          { day: 2, title: "Burj Khalifa & Downtown", desc: "Visit Burj Khalifa top floor, Dubai Mall, Dubai Fountain show." },
          { day: 3, title: "Desert Safari", desc: "Dune bashing, camel ride, BBQ dinner under the stars." },
          { day: 4, title: "Palm Jumeirah & Atlantis", desc: "Monorail ride, Aquaventure waterpark, The Pointe visit." },
          { day: 5, title: "Gold & Spice Souk", desc: "Old Dubai heritage tour, abra ride, souk shopping." },
          { day: 6, title: "Departure", desc: "Breakfast, leisure time, airport drop." },
        ],
        includes: ["Return flights", "5-star hotel", "Daily breakfast", "All transfers", "Visa assistance"],
      },
      {
        id: "europe-8n",
        title: "European Dream",
        destination: "Paris + Switzerland",
        duration: "8N / 9D",
        price: "₹1,20,000",
        image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
        highlights: ["Eiffel Tower", "Swiss Alps", "Rhine Falls", "Louvre Museum", "Lake Geneva"],
        itinerary: [
          { day: 1, title: "Arrive Paris", desc: "Airport pickup, Eiffel Tower night view." },
          { day: 2, title: "Paris City Tour", desc: "Louvre, Notre Dame, Champs-Élysées, Seine cruise." },
          { day: 3, title: "Versailles", desc: "Palace of Versailles day trip, Hall of Mirrors." },
          { day: 4, title: "Train to Switzerland", desc: "High-speed train, Zurich check-in, old town walk." },
          { day: 5, title: "Jungfraujoch", desc: "Top of Europe excursion, Interlaken views." },
          { day: 6, title: "Lucerne", desc: "Lion Monument, Chapel Bridge, Lake Lucerne boat ride." },
          { day: 7, title: "Geneva", desc: "Jet d'Eau, CERN area, luxury shopping." },
          { day: 8, title: "Rhine Falls", desc: "Europe's largest waterfall, farewell dinner." },
          { day: 9, title: "Departure", desc: "Airport transfer, flight home." },
        ],
        includes: ["Return flights", "4-star hotels", "Breakfast & dinner", "Rail passes", "Schengen visa"],
      },
    ],
  },
  {
    id: "beach-escapes",
    label: "Beach Escapes",
    tagline: "Sun, sand & crystal waters",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    color: "#00b4d8",
    packages: [
      {
        id: "maldives-4n",
        title: "Maldives Paradise",
        destination: "Maldives",
        duration: "4N / 5D",
        price: "₹85,000",
        image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80",
        highlights: ["Overwater Villa", "Snorkeling", "Sunset Cruise", "Dolphin Watch", "Spa"],
        itinerary: [
          { day: 1, title: "Arrival & Speedboat Transfer", desc: "Arrive Malé, speedboat to resort, welcome drink." },
          { day: 2, title: "Water Activities", desc: "Snorkeling, kayaking, glass-bottom boat tour." },
          { day: 3, title: "Dolphin Cruise & Spa", desc: "Morning dolphin watching cruise, afternoon spa session." },
          { day: 4, title: "Island Hopping", desc: "Local island visit, sandbank picnic, sunset cruise." },
          { day: 5, title: "Departure", desc: "Leisure morning, speedboat to Malé, fly home." },
        ],
        includes: ["Return flights", "Overwater bungalow", "All meals", "Speedboat transfers", "Snorkel gear"],
      },
      {
        id: "bali-5n",
        title: "Bali Bliss",
        destination: "Bali, Indonesia",
        duration: "5N / 6D",
        price: "₹55,000",
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
        highlights: ["Tanah Lot", "Ubud Rice Terraces", "Kuta Beach", "Mount Batur", "Uluwatu"],
        itinerary: [
          { day: 1, title: "Arrive Bali", desc: "Airport pickup, Seminyak hotel, Kuta beach sunset." },
          { day: 2, title: "Ubud Culture", desc: "Monkey forest, Tegallalang rice terraces, traditional dance." },
          { day: 3, title: "Mount Batur Sunrise", desc: "Early morning volcano trek, breakfast at summit." },
          { day: 4, title: "Tanah Lot & Uluwatu", desc: "Sea temples, cliff-top sunset, Kecak dance." },
          { day: 5, title: "Beach & Spa", desc: "Nusa Dua beach, traditional Balinese massage." },
          { day: 6, title: "Departure", desc: "Souvenir shopping, airport transfer." },
        ],
        includes: ["Return flights", "Villa stay", "Daily breakfast", "All transfers", "Visa on arrival"],
      },
    ],
  },
  {
    id: "honeymoon-trips",
    label: "Honeymoon Trips",
    tagline: "Romance crafted just for two",
    coverImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    color: "#ff6b9d",
    packages: [
      {
        id: "maldives-honeymoon",
        title: "Maldives Honeymoon",
        destination: "Maldives",
        duration: "5N / 6D",
        price: "₹1,10,000",
        image: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=600&q=80",
        highlights: ["Private Villa", "Candlelight Dinner", "Couples Spa", "Sunset Cruise", "Snorkeling"],
        itinerary: [
          { day: 1, title: "Romantic Arrival", desc: "Rose petal welcome, champagne, overwater villa check-in." },
          { day: 2, title: "Underwater World", desc: "Private snorkeling tour, marine life discovery." },
          { day: 3, title: "Couples Spa Day", desc: "Full-day spa retreat, couple's massage, jacuzzi." },
          { day: 4, title: "Sunset Sailing", desc: "Private dhoni cruise, candlelight beach dinner." },
          { day: 5, title: "Island Picnic", desc: "Private sandbank picnic, photography session." },
          { day: 6, title: "Farewell", desc: "Breakfast in bed, leisure, departure." },
        ],
        includes: ["Flights", "Overwater villa", "All meals", "Private transfers", "Honeymoon decor"],
      },
      {
        id: "paris-honeymoon",
        title: "Paris Romance",
        destination: "Paris, France",
        duration: "6N / 7D",
        price: "₹1,40,000",
        image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
        highlights: ["Eiffel Tower Dinner", "Seine Cruise", "Montmartre", "Champagne Tour", "Louvre"],
        itinerary: [
          { day: 1, title: "Arrive Paris", desc: "Luxury hotel, evening Eiffel Tower light show." },
          { day: 2, title: "City of Love", desc: "Louvre, Notre Dame, Luxembourg Gardens." },
          { day: 3, title: "Versailles", desc: "Palace gardens, romantic picnic, sunset wine." },
          { day: 4, title: "Montmartre", desc: "Sacré-Cœur, artist quarter, cabaret show." },
          { day: 5, title: "Champagne Country", desc: "Day trip to Champagne region, wine tasting." },
          { day: 6, title: "Seine Dinner Cruise", desc: "Romantic dinner cruise, final Paris evening." },
          { day: 7, title: "Departure", desc: "Breakfast, airport transfer." },
        ],
        includes: ["Flights", "Boutique hotel", "Breakfast + 2 dinners", "All transfers", "Schengen visa"],
      },
    ],
  },
  {
    id: "family-tours",
    label: "Family Tours",
    tagline: "Memories for the whole family",
    coverImage: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    color: "#ff9a00",
    packages: [
      {
        id: "singapore-family",
        title: "Singapore Family Fun",
        destination: "Singapore",
        duration: "5N / 6D",
        price: "₹70,000",
        image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80",
        highlights: ["Universal Studios", "Gardens by the Bay", "Sentosa Island", "Night Safari", "Marina Bay Sands"],
        itinerary: [
          { day: 1, title: "Arrive Singapore", desc: "Hotel check-in, Marina Bay Sands view, dinner." },
          { day: 2, title: "Universal Studios", desc: "Full day at Universal Studios, Sentosa cable car." },
          { day: 3, title: "Gardens & Science Museum", desc: "Gardens by the Bay, Science Centre, Cloud Forest." },
          { day: 4, title: "Night Safari", desc: "Singapore Zoo, world's first Night Safari experience." },
          { day: 5, title: "Chinatown & Shopping", desc: "Cultural heritage walk, Orchard Road shopping." },
          { day: 6, title: "Departure", desc: "Leisure breakfast, airport transfer." },
        ],
        includes: ["Flights", "Family room hotel", "Breakfast daily", "Theme park tickets", "All transfers"],
      },
    ],
  },
  {
    id: "adventure-tours",
    label: "Adventure Tours",
    tagline: "Thrills beyond the ordinary",
    coverImage: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&q=80",
    color: "#c7d300",
    packages: [
      {
        id: "nepal-trek",
        title: "Nepal Himalaya Trek",
        destination: "Nepal",
        duration: "7N / 8D",
        price: "₹50,000",
        image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
        highlights: ["Everest Base Camp View", "Annapurna Trek", "Pokhara Lake", "Paragliding", "Bungee Jump"],
        itinerary: [
          { day: 1, title: "Arrive Kathmandu", desc: "Hotel, Thamel exploration, briefing." },
          { day: 2, title: "Kathmandu Valley", desc: "Pashupatinath, Boudhanath, Swayambhunath." },
          { day: 3, title: "Fly to Pokhara", desc: "Mountain flight, lakeside walk, sunset view." },
          { day: 4, title: "Annapurna Trek Day 1", desc: "Trek to Ghandruk, rhododendron forests." },
          { day: 5, title: "Annapurna Trek Day 2", desc: "Poon Hill sunrise, Himalaya panorama." },
          { day: 6, title: "Paragliding", desc: "Tandem paragliding over Pokhara Valley." },
          { day: 7, title: "Bungee & White Water", desc: "Bhote Koshi bungee jump, river rafting." },
          { day: 8, title: "Departure", desc: "Kathmandu, souvenir shopping, airport." },
        ],
        includes: ["Flights", "Trekking lodge stay", "All meals on trek", "Guide & porter", "Permits"],
      },
    ],
  },
  {
    id: "luxury-holidays",
    label: "Luxury Holidays",
    tagline: "Ultra-premium travel experiences",
    coverImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    color: "#ffd700",
    packages: [
      {
        id: "maldives-luxury",
        title: "Maldives Ultra Luxury",
        destination: "Maldives",
        duration: "6N / 7D",
        price: "₹2,50,000",
        image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80",
        highlights: ["Private Water Villa", "Butler Service", "Submarine Tour", "Private Chef", "Helicopter Transfer"],
        itinerary: [
          { day: 1, title: "Helicopter Arrival", desc: "Private helicopter transfer, champagne welcome." },
          { day: 2, title: "Private Underwater Dining", desc: "Exclusive underwater restaurant experience." },
          { day: 3, title: "Submarine Excursion", desc: "Private submarine tour of coral reefs." },
          { day: 4, title: "Yacht Charter", desc: "Full-day private yacht, fishing, snorkeling." },
          { day: 5, title: "Spa & Wellness", desc: "Over-water spa pavilion, meditation, yoga." },
          { day: 6, title: "Private Island Picnic", desc: "Exclusive private island, chef-prepared lunch." },
          { day: 7, title: "Departure", desc: "Helicopter to Malé, first-class flight home." },
        ],
        includes: ["Business class flights", "Private water villa", "Full board + butler", "All excursions", "Helicopter transfers"],
      },
    ],
  },
  {
    id: "group-tours",
    label: "Group Tours",
    tagline: "Travel together, save more",
    coverImage: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=800&q=80",
    color: "#25D366",
    packages: [
      {
        id: "europe-group",
        title: "Europe Group Special",
        destination: "5 Countries",
        duration: "12N / 13D",
        price: "₹95,000",
        image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=80",
        highlights: ["5 Countries", "Guided Tours", "Group Transport", "24/7 Tour Manager", "Cultural Experiences"],
        itinerary: [
          { day: 1, title: "Arrive Amsterdam", desc: "Group meet, canal cruise, Anne Frank House." },
          { day: 2, title: "Amsterdam", desc: "Rijksmuseum, Vondelpark, diamond factory." },
          { day: 3, title: "Brussels", desc: "Grand Place, Manneken Pis, waffle tasting." },
          { day: 4, title: "Paris", desc: "Eiffel Tower, Louvre, Seine cruise." },
          { day: 5, title: "Paris Day 2", desc: "Versailles palace, Montmartre, shopping." },
          { day: 6, title: "Swiss Border", desc: "Train to Zurich, old town, Rhine Falls." },
          { day: 7, title: "Lucerne", desc: "Lion Monument, Mt Pilatus cable car." },
          { day: 8, title: "Interlaken", desc: "Jungfraujoch, paragliding option." },
          { day: 9, title: "Milan", desc: "Duomo, Galleria Vittorio, fashion district." },
          { day: 10, title: "Venice", desc: "Gondola ride, St Mark's Basilica, island tour." },
          { day: 11, title: "Rome", desc: "Colosseum, Vatican, Trevi Fountain." },
          { day: 12, title: "Rome Day 2", desc: "Spanish Steps, Pantheon, farewell dinner." },
          { day: 13, title: "Departure", desc: "Airport transfer, fly home." },
        ],
        includes: ["Flights", "3-star hotels", "Daily breakfast", "Coach transport", "Tour manager", "Schengen visa"],
      },
    ],
  },
  {
    id: "weekend-getaways",
    label: "Weekend Getaways",
    tagline: "Quick escapes, big memories",
    coverImage: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
    color: "#c7d300",
    packages: [
      {
        id: "thailand-weekend",
        title: "Bangkok Weekend",
        destination: "Bangkok, Thailand",
        duration: "3N / 4D",
        price: "₹28,000",
        image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80",
        highlights: ["Grand Palace", "Floating Market", "Tuk-Tuk Tour", "Rooftop Bar", "Street Food"],
        itinerary: [
          { day: 1, title: "Arrive Bangkok", desc: "Hotel check-in, Khao San Road, rooftop dinner." },
          { day: 2, title: "Temples & Palace", desc: "Grand Palace, Wat Pho, Chao Phraya river cruise." },
          { day: 3, title: "Floating Market", desc: "Damnoen Saduak market, tuk-tuk city tour, night market." },
          { day: 4, title: "Departure", desc: "Chatuchak market, airport transfer." },
        ],
        includes: ["Flights", "4-star hotel", "Breakfast", "Airport transfers", "Visa on arrival"],
      },
    ],
  },
  {
    id: "customized-trips",
    label: "Customized Trips",
    tagline: "Your dream trip, your way",
    coverImage: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&q=80",
    color: "#c7d300",
    packages: [
      {
        id: "custom-plan",
        title: "Build Your Own Trip",
        destination: "Any Destination",
        duration: "Custom",
        price: "On Request",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=80",
        highlights: ["Any Destination", "Custom Itinerary", "Flexible Dates", "Any Budget", "Personal Travel Expert"],
        itinerary: [
          { day: 1, title: "Consultation", desc: "Share your dream destination, dates, and budget with our expert." },
          { day: 2, title: "Itinerary Design", desc: "We craft a personalised day-by-day itinerary for you." },
          { day: 3, title: "Review & Adjust", desc: "Review the plan, make any changes you'd like." },
          { day: 4, title: "Booking & Visa", desc: "We handle all bookings, visa applications, and documentation." },
          { day: 5, title: "Travel Support", desc: "24/7 support throughout your journey." },
        ],
        includes: ["Custom flights", "Hotel of your choice", "Meals as preferred", "All transfers", "Visa assistance"],
      },
    ],
  },
  {
    id: "cruise-packages",
    label: "Cruise Packages",
    tagline: "Sail into the extraordinary",
    coverImage: "https://images.unsplash.com/photo-1548032885-b5e38734688a?w=800&q=80",
    color: "#0077b6",
    packages: [
      {
        id: "mediterranean-cruise",
        title: "Mediterranean Cruise",
        destination: "Italy + Greece + Turkey",
        duration: "7N / 8D",
        price: "₹1,80,000",
        image: "https://images.unsplash.com/photo-1548032885-b5e38734688a?w=600&q=80",
        highlights: ["Rome Port", "Santorini", "Mykonos", "Istanbul", "Barcelona"],
        itinerary: [
          { day: 1, title: "Embark Rome (Civitavecchia)", desc: "Board cruise ship, sail-away party." },
          { day: 2, title: "Naples & Pompeii", desc: "Shore excursion to ancient Pompeii ruins." },
          { day: 3, title: "Santorini", desc: "Blue domes, caldera views, sunset dinner." },
          { day: 4, title: "Mykonos", desc: "Windmills, Little Venice, beach clubs." },
          { day: 5, title: "Athens (Piraeus)", desc: "Acropolis, Parthenon, Plaka district." },
          { day: 6, title: "Istanbul", desc: "Hagia Sophia, Grand Bazaar, Bosphorus view." },
          { day: 7, title: "Sea Day", desc: "Onboard activities, pools, shows, fine dining." },
          { day: 8, title: "Disembark Barcelona", desc: "Barceloneta beach, Sagrada Família option, fly home." },
        ],
        includes: ["Cruise cabin", "All meals onboard", "Entertainment", "Port taxes", "Flights to/from"],
      },
    ],
  },
];